version: '3'
services:
  postgres:
    container_name: postgres-chruchdb
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: chruchdb
